<?/*
	
site_name	EarnTalks
site_url	http://earntalks.webege.com
site_url_alt	http://earntalks.webege.com
site_logo_url	images/logo.png
system_email	earntalks.com@gmail.com
admin_email	earntalks.com@gmail.com
hostname	mysql14.000webhost.com
database	a1097319_et
db_login	a1097319_et
db_pass	andrei0723
admin_lr_account	U8529781
admin_pm_account	U1817689
admin_pm_name	EarnTalks.com
admin_ym_account	freelancer0723
alexa	1
admin_password	andrea23
payments	LibertyReserve,PerfectMoney,C-Gold,Webmoney,E-Gold,SolidTrustPay,StrictPay,ECUMoney,GlobalDigitalPay,V-Money,Paypal,Pecunix,AlertPay,EuroPay,WesternUnion,EVOWall,Bankwire,ssl,ddos
search_box	1
search_box_pos	1
ecurrency_box	1
ecurrency_box_pos	1
admin_ym_account_box	1
admin_ym_account_box_pos	0
rcb_box	1
rcb_box_pos	1
top10_box	1
top10_box_pos	0
newlistings_box	1
newlistings_box_pos	1
lastestpayout_box	1
lastestpayout_box_pos	0
lastestvote_box	1
lastestvote_box_pos	1
paysystems_box	1
paysystems_box_pos	1
login_box	1
login_box_pos	1
textads_box	1
textads_box_pos	1
minibanner_box	1
minibanner_box_pos	0
subscribe_box	1
subscribe_box_pos	0
logo_box	1
logo_box_pos	0
visitor_statistic_box	1
visitor_statistic_box_pos	0
partners_box	1
partners_box_pos	0
news_box	1
last_news_count	6
listing_confirmation_require	0
notify_about_addition	1
vote_confirmation_require	0
new_for_days	10
new_page_for_days	100
traffic_count_days	7
admin_login	EarnTalks
image_bg_color	fffff2
image_name_bg_color	#FFFFFF
image_text_color	#000000
demomode	0
license	
premiummonitorfees	50
premiumlistingfees	10
normalmonitorfees	20
normallistingfees	8
trialmonitorfees	10
triallistingfees	5
autosurfmonitorfees	50
autosurflistingfees	10
gptmonitorfees	10
gptlistingfees	0
alex	1
*/?>
