<br><div class="list_text"><div align="center"><img src="images/t1.gif" align="absMiddle"> <a class="list_menu">Week traffic</a>
<hr size=1 noshade="noshade" style="border:1px #cccccc dotted"></div>

<table width="100%">
<tr><td width="50%" style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">Details page  views</td><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">{$details_views}</td></tr>
<tr><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">Hits in</td><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">{$hits_in}</td></tr>
<tr><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">Hits out</td><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">{$hits_out}</td></tr>
<tr><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">Site hits</td><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">{$hits}</td></tr>
<tr><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">Site hosts</td><td style="padding:5px; font-family: Tahoma; font-size: 11px; padding:5px; border-bottom:#c8c8c8 1px solid;border-right:#c8c8c8 1px solid;border-left:#c8c8c8 1px solid;">{$hosts}</td></tr>
</table>